import * as z from "zod"

export const PostModel = z.object({
  /**
   * The unique identifier for the post
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * A brief title that describes the contents of the post
   */
  title: z.string().max(255, { message: "The title must be shorter than 256 characters" }),
  /**
   * The main content of the post
   */
  content: z.string(),
  /**
   * The date and time when the post was created
   */
  createdAt: z.date().optional(),
})
